### ISSUE TITLE
ERROR Cannot create issue. Does your token have scope repo?

### ISSUE THREAD

**Issue by iljah** [vsoch/helpme#20]
I couldn't submit issues to this repo with helpme, it always answered with ERROR Cannot create issue. Does your token have scope repo?
This happened even with token that had all permissions that I could give it. According to https://gist.github.com/JeffPaine/3145490 in order to file issues (with API only?) user must have write access to target repo.

Apparently there are github apps and 0auth apps (https://github.com/dear-github/dear-github/issues/113#issuecomment-365121631), maybe switching to the other would allow submitting issues to other people's repositories?..

**Comment by vsoch** [comment]
hey @iljah ! This was a bug! See #15. The bug is fixed, and the Docker container is also rebuilding. You can check it's status here if you want to test using it --> https://hub.docker.com/r/vanessa/helpme/builds/

I'm going to close the issue as fixed and please re-open if you have any more trouble.

**Comment by vsoch** [comment]
And I believe that a personal access token is a kind of OAuth call, but I can't find where I read that atm!
