### ISSUE TITLE
interface image in README

### ISSUE THREAD

**Issue by pdurbin** [vsoch/helpme#45]
Hi! I'm confused by the interface image added to the README in b438b11. It lead me to believe that helpme has a GUI. Is the interface simply a screenshot of the documentation? If so, perhaps the image could me moved lower down under "Usage" with a note that says something like "Here's a screenshot of our docs" or whatever. Am I making sense? 😄 Seems like a great project! I learned about it at https://ask.cyberinfrastructure.org/t/programmatic-access-via-api/580

Oh, another thought is to replace it with one of those fancy animated gifs made by https://asciinema.org (or however they make them). A lot of time they show command line tools in action.

**Comment by vsoch** [comment]
That is just the documentation interface, served at https://vsoch.github.io/helpme. It's the closest thing to a logo / branding that I have, so I put it there.

I'd be happy to make this change for you! It's funny you mention this, because my original idea for helpme was a server application that users would push questions to (akin to Git) but I changed to a command line tool to push to places where the questions would be wanted (like GitHub, discourse, etc.)

**Comment by vsoch** [comment]
I just removed the image - take a look and let me know if it's good! :)

And if you have ideas / requests for other helpers (meaning an endpoint that people like to post to) please let me know!

**Comment by pdurbin** [comment]
@vsoch looks great! Thanks for resolving this so quickly!
